steps:
  # Paso 1: Construir la imagen de Docker (El Taxi)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mi-web', '.']

  # Paso 2: Guardar la imagen en Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mi-web']

  # Paso 3: ¡Desplegar en Cloud Run!
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mi-primera-web' # Este será el nombre de tu servicio
      - '--image'
      - 'gcr.io/$PROJECT_ID/mi-web'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated' # Para que sea público en internet